// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD0tIe4oP1hn3ooT8PdlRJk-NT_SVRnxc',
    appId: '1:648963347584:web:3d4d9f12f5604f28774265',
    messagingSenderId: '648963347584',
    projectId: 'gemini-test-1173a',
    authDomain: 'gemini-test-1173a.firebaseapp.com',
    storageBucket: 'gemini-test-1173a.firebasestorage.app',
    measurementId: 'G-90XLF7SPXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS1ODcRlMyKGLwHPfTNdzT2Bn2MszWLsw',
    appId: '1:648963347584:android:87308d550acfeabe774265',
    messagingSenderId: '648963347584',
    projectId: 'gemini-test-1173a',
    storageBucket: 'gemini-test-1173a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaPQG42oJnzUG6JytrTCb8vgHSSsbUoQw',
    appId: '1:648963347584:ios:9de1edd395ab3472774265',
    messagingSenderId: '648963347584',
    projectId: 'gemini-test-1173a',
    storageBucket: 'gemini-test-1173a.firebasestorage.app',
    iosBundleId: 'com.example.introToGenui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaPQG42oJnzUG6JytrTCb8vgHSSsbUoQw',
    appId: '1:648963347584:ios:9de1edd395ab3472774265',
    messagingSenderId: '648963347584',
    projectId: 'gemini-test-1173a',
    storageBucket: 'gemini-test-1173a.firebasestorage.app',
    iosBundleId: 'com.example.introToGenui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOQOi7YkzQnQRqJCUvtCC0r3EKwmGg8I0',
    appId: '1:648963347584:web:2188442501166a3e774265',
    messagingSenderId: '648963347584',
    projectId: 'gemini-test-1173a',
    authDomain: 'gemini-test-1173a.firebaseapp.com',
    storageBucket: 'gemini-test-1173a.firebasestorage.app',
    measurementId: 'G-GEVD4V1ZRB',
  );
}
